name: pikapika
description: A cross platform comic client.
publish_to: 'none'

version: 1.8.16+40

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  isolate: ^2.1.1
  event: ^2.0.5
  flutter_svg: ^1.0.3
  flutter_styled_toast: 2.0.0
  another_xlider: ^1.0.1+2
  scrollable_positioned_list: ^0.2.0-nullsafety.0
  permission_handler: ^10.1.0
  url_launcher: ^6.0.9
  clipboard: ^0.1.3
  photo_view: 0.14.0
  multi_select_flutter: ^4.0.0
  # flutter_datetime_picker: 1.5.1
  modal_bottom_sheet: ^3.0.0-pre
  image_cropper: 1.5.0
  image_picker: ^0.8.6
  file_picker: 5.2.5
  crop_image: 1.0.2
  image: ^3.1.3
  path: ^1.8.0
  uri_to_file: ^0.2.0
  uni_links: ^0.5.1
  filesystem_picker: ^3.0.0-beta.1
  easy_localization: ^3.0.7+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true
  assets:
    - lib/assets/
    - lib/assets/translations/
